# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170824_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
