# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170824_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
